name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, pdo_sqlite
        ini-values: post_max_size=256M, upload_max_filesize=256M
        coverage: none # or xdebug, pcov
    - name: Install Dependencies
      run: composer install --prefer-dist --no-interaction --no-progress
    - name: Run Tests
      run: php artisan test
    - name: Deploy (contoh sederhana)
      if: github.ref == 'refs/heads/main'
      run: echo "Deploying to production..."
      # Di sini Anda bisa menambahkan langkah-langkah deployment sebenarnya,
      # seperti SSH ke server, rsync, atau menggunakan layanan deployment.